/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Simple-PostgreSQL-Client.h
 #	source generated by 4D Plugin Wizard
 #	Project : Simple PostgreSQL Client
 #	author : miyako
 #	2020/02/25
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SIMPLE_POSTGRESQL_CLIENT_H
#define PLUGIN_SIMPLE_POSTGRESQL_CLIENT_H

#include "4DPluginAPI.h"
#include "libpq-fe.h"
#include "ARRAY_TEXT.h"
#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#include "4DPlugin-JSON.h"

#if VERSIONMAC
extern unsigned char pg_tolower(unsigned char ch);
extern bool pg_strong_random(void *buf, size_t len);
#include <iconv.h>
#define UTF32NATIVE "UTF-32LE"
#endif

#define NDEBUG

#pragma mark -

void PQ_EXECUTE(PA_PluginParameters params);

#endif /* PLUGIN_SIMPLE_POSTGRESQL_CLIENT_H */
